name: MSBuild

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: CP_Main_10.sln

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set the value
        run: |
          $buildNumber = ${{ github.run_number }} + 136
          echo "VERSION_FILENAME=3_25_${buildNumber}_0" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "VERSION_DOT_FILENAME=3.25.${buildNumber}.0" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}
      - name: Build
        run: msbuild CP_Main_10.sln /p:Configuration=Release /p:Platform=x64
      - name: Set Versions
        run: |
            DittoSetup\rcedit-x64 Release64\Ditto.exe --set-file-version ${{env.VERSION_DOT_FILENAME}} --set-product-version ${{env.VERSION_DOT_FILENAME}}
      - name: upload-unsigned-exe
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-exe
          retention-days: 1
          path: |
            Release64\Ditto.exe
            Release64\ICU_Loader.dll
            Release64\Addins\DittoUtil.dll
      - name: Build Portable
        run: |
            DittoSetup\BuildPortableZIP.bat "DittoPortable_${{env.VERSION_FILENAME}}" bit64
      - name: upload-portable
        uses: actions/upload-artifact@v4
        with:
          name: portable-zip
          path: DittoSetup\output\DittoPortable_${{env.VERSION_FILENAME}}.zip
